// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDihfk8CjP6Og7n6f_WfuILYqSZ05-jUb8',
    appId: '1:808298191659:web:c03e3b3367a7060021c36e',
    messagingSenderId: '808298191659',
    projectId: 'jinfamily-1cda5',
    authDomain: 'jinfamily-1cda5.firebaseapp.com',
    storageBucket: 'jinfamily-1cda5.appspot.com',
    measurementId: 'G-DHYGG3GEGN',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD7g0q9RI5NUIBQmiSuQ1ef6FakXxuXtOg',
    appId: '1:808298191659:android:b350c77b60b3cdac21c36e',
    messagingSenderId: '808298191659',
    projectId: 'jinfamily-1cda5',
    storageBucket: 'jinfamily-1cda5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDRY-MWjruOWLSy2bs6gCKITxsJKFuW9cc',
    appId: '1:808298191659:ios:bd33c7b342001a7721c36e',
    messagingSenderId: '808298191659',
    projectId: 'jinfamily-1cda5',
    storageBucket: 'jinfamily-1cda5.appspot.com',
    iosBundleId: 'com.example.jinApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDRY-MWjruOWLSy2bs6gCKITxsJKFuW9cc',
    appId: '1:808298191659:ios:eeb4a9fae545a1d821c36e',
    messagingSenderId: '808298191659',
    projectId: 'jinfamily-1cda5',
    storageBucket: 'jinfamily-1cda5.appspot.com',
    iosBundleId: 'com.example.jinApp.RunnerTests',
  );
}
